name: Terraform flow

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Initialize
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Plan Terraform
        id: plan
        env:
          TF_VAR_name:                 ${{ secrets.NAME }}
          TF_VAR_vpc_cidr:             ${{ secrets.VPC_CIDR }}
          TF_VAR_single_nat_gateway:   ${{ secrets.SINGLE_NAT_GATEWAY }}
          TF_VAR_subnet_count:         ${{ secrets.SUBNET_COUNT }}
          TF_VAR_app_repository:       ${{ secrets.APP_REPOSITORY }}
          TF_VAR_terraform_repository: ${{ secrets.TERRAFORM_REPOSITORY }}
        run: terraform plan -input=false -no-color
